### PR TITLE
Update data schema

### PR DESCRIPTION
**Pull request by TheConnMan**
I've updated the data schema as we discussed a while ago. I've verified that the auto-generated MySQL tables are correct as well.

I did make some modifications which I want confirmation on. A few notes on the current schema:
- We have three many-to-many relationships: User/League, Team/Game, User/Team
- Two of these are managed by us (via the `UserLeague` and `TeamGame` objects)
- Only `TeamGame` has a reason to be managed by us (the `wins` field on the join object), but I kept the `UserLeague` object in case we want to add an `enabled` flag or something to it in case someone is booted from the team. If this is not necessary then we should let Sails manage this relationship and remove the `UserLeague` object

Let me know any thoughts on the current many-to-many relationships and if you think I missed any.

### CODE REVIEW

**Review by Grumblesmith — APPROVED** [review]
Looks good to me. I do think we'll want to add an "enabled" flag to UserLeague at some point to be able to control league membership.

**Comment by SirZach** [comment]
I don't think we'll need to worry about booting players from teams. Seems like an edge case we don't need to try and prepare for now. Lg2m!

**Review by SirZach — APPROVED** [review]

**Comment by TheConnMan** [comment]
@SirZach So you want to remove the `UserLeague` object because you don't think we should worry about booting users? That conflicts with what I think @Createor is recommending.

**Comment by SirZach** [comment]
I was saying we don't need to worry about booting players from teams, not from leagues.

**Pull request merged**
